### ISSUE TITLE
Weird seperation lines.

### ISSUE THREAD

**Issue by Xrey274** [A5b84/armor-chroma-fabric#10]
![image](https://user-images.githubusercontent.com/30723811/149820367-124ead49-7d2f-44a0-8311-8bac1715f766.png)
Yes I do have a texture pack, but even without it the lines remain.

**Comment by EGOIST1372** [comment]
that doesn't look like a bug to me. I guess that separation line is for each piece of armor you have and it needed to do that to separate each piece of armor individually

**Comment by A5b84** [comment]
Yep I'd say it's more of a side effect than a bug, but I think it would be nice to have an option to remove them

**Comment by A5b84** [comment]
Update: this will be fixed in the next version (but there won't be an option for that as I can't reasonably imagine why someone would want useless lines back)

**Comment by A5b84** [comment]
Update: said next version has been released
