### ISSUE TITLE
higher resolution resource packs don't work

### ISSUE THREAD

**Issue by JumperREDACTED** [A5b84/armor-chroma-fabric#17]
I tried using a resource pack with higher resolution icons because I normally use a 32x resource pack. It showed up in the resource pack menu, but didn't apply ingame.
Unpacking the mod and replacing the "alternative icons"'s armor_chroma.png worked fine.
A 16x resource pack I made to test worked fine too.

The packs:
[ArmorChroma test 16x.zip](https://github.com/A5b84/armor-chroma-fabric/files/10859048/test.16x.zip)
[ArmorChroma 32x.zip](https://github.com/A5b84/armor-chroma-fabric/files/10859049/ArmorChroma.32x.zip)

**Comment by A5b84** [comment]
Works fine on my machine, not sure if it's related but your 16x.zip pack contains 32x32 textures and your 32x.zip contains 16x16 textures
![image](https://user-images.githubusercontent.com/42934711/229356663-31fb72c3-483b-42d8-ae85-49e87c3c334e.png)
