### ISSUE TITLE
Remove Stripes

### ISSUE THREAD

**Issue by QueenUlyana** [A5b84/armor-chroma-fabric#19]
Please give me the opportunity to remove these stripes. They spoil the whole view. 
![2023-05-19_21 53 53](https://github.com/A5b84/armor-chroma-fabric/assets/83131824/ae382b31-5b4e-4469-8b02-203ca6f52835)
![2023-05-19_21 54 49](https://github.com/A5b84/armor-chroma-fabric/assets/83131824/0d16e64c-8155-440c-b9d2-f56e0555e584)

**Comment by A5b84** [comment]
See #10

**Comment by QueenUlyana** [comment]
> See #10

So the end you didn't add the ability to remove these bars. I would have liked to be able to do it.
