### ISSUE TITLE
Allow customizing the glint color

### ISSUE THREAD

**Issue by Nightcaat** [A5b84/armor-chroma-fabric#20]

**Comment by YoshiRulz** [comment]
It uses the same texture as enchanted items, so you can swap it out with a resource pack. [Here's an example](https://github.com/A5b84/armor-chroma-fabric/files/14184381/greenglint.zip).

**Comment by A5b84** [comment]
Changing it with a resource pack is probably a better option than having the mod do it (especially if you want a glint with multiple colors) so I'll close this
