### ISSUE TITLE
Put this mod in Modrinth

### ISSUE THREAD

**Issue by bxvcd-732** [A5b84/armor-chroma-fabric#4]
This mod is amazing, and I hope many people to know this amazing mod too. It would be great for this mod to be in [Modrinth](https://modrinth.com/) since it will be easier for people to use this mod.

**Comment by A5b84** [comment]
I'd like to get permission from jobicade first, I've sent them a message about that not too long ago

**Comment by eunsoule** [comment]
Cool! It would be great to see this mod on Modrinth.

**Comment by A5b84** [comment]
Somewhat related update: the mod is now available on curseforge [here](https://www.curseforge.com/minecraft/mc-mods/armor-chroma-for-fabric), I'll probably put it on Modrinth too at some point in the future

**Comment by A5b84** [comment]
Link: https://modrinth.com/mod/armor-chroma-for-fabric
