### ISSUE TITLE
Incompatibility with Semitranslucency Fix - enchanted armor is pitch black

### ISSUE THREAD

**Issue by Khodyn** [A5b84/armor-chroma-fabric#7]
![image](https://user-images.githubusercontent.com/49518050/144725868-0c8d1e4f-0246-4c17-b30c-6771bd8d2b11.png)
[Semitranslucency Fix](https://github.com/ruvaldak/Semitranslucency)

**Comment by A5b84** [comment]
Fixed in v1.2.0
